## Импорты и загрузка датасета

In [62]:
import pandas as pd
import numpy as np
import optuna

from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_auc_score, f1_score

from catboost import CatBoostClassifier, Pool, metrics
from lightgbm import LGBMClassifier

In [1]:
RANDOM_STATE = 111
DATASET_PATH = 'https://raw.githubusercontent.com/evgpat/edu_stepik_practical_ml/main/datasets/flight_delays_train.csv'

In [3]:
data = pd.read_csv(DATASET_PATH)

In [8]:
X = data.drop("dep_delayed_15min", axis = 1)
y = data["dep_delayed_15min"] == 'Y' ## Чтобы в столбце целевой переменной были не 'Y' и 'N', а True и False

In [9]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Month          100000 non-null  str
 1   DayofMonth     100000 non-null  str
 2   DayOfWeek      100000 non-null  str
 3   DepTime        100000 non-null  int64
 4   UniqueCarrier  100000 non-null  str
 5   Origin         100000 non-null  str
 6   Dest           100000 non-null  str
 7   Distance       100000 non-null  int64
dtypes: int64(2), str(6)
memory usage: 6.1 MB

In [10]:
X.describe()

             DepTime      Distance
count  100000.000000  100000.00000
mean     1341.523880     729.39716
std       476.378445     574.61686
min         1.000000      30.00000
25%       931.000000     317.00000
50%      1330.000000     575.00000
75%      1733.000000     957.00000
max      2534.000000    4962.00000

In [11]:
X.head()

  Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0   c-8       c-21       c-7     1934            AA    ATL  DFW       732
1   c-4       c-20       c-3     1548            US    PIT  MCO       834
2   c-9        c-2       c-5     1422            XE    RDU  CLE       416
3  c-11       c-25       c-6     1015            OO    DEN  MEM       872
4  c-10        c-7       c-6     1828            WN    MDW  OMA       423

## Создадим список номеров колонок с категориальными признаками для бустингов

Какой длины получился список?

In [21]:
X.dtypes

Month              str
DayofMonth         str
DayOfWeek          str
DepTime          int64
UniqueCarrier      str
Origin             str
Dest               str
Distance         int64
dtype: object

In [19]:
categorical_features_indices = np.where(X.dtypes != 'int64')[0]

In [22]:
len(categorical_features_indices)

6

## Поделим данные на трейн и тест

In [74]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.25, random_state=RANDOM_STATE)

In [25]:
Xtrain.head()

      Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
41207   c-4       c-18       c-1     1457            CO    EWR  TPA       998
28283  c-11        c-1       c-2     1225            UA    DEN  BOS      1754
34619   c-6       c-16       c-5     1650            YV    IAD  CAE       401
8789    c-5       c-18       c-4      923            AA    SLC  DFW       988
38315   c-2       c-14       c-2     1839            AA    STL  SAN      1558

## Модели с параметрами по умолчанию

### CatBoost

In [37]:
model = CatBoostClassifier(
    custom_loss=['AUC'],
    random_seed=RANDOM_STATE
)

model.fit(
    Xtrain, ytrain,
    cat_features=categorical_features_indices,
    logging_level='Silent', 
    plot = True
)

pred = model.predict_proba(Xtest)[:, 1] 

roc_auc_score(ytest, pred)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0.7671857694659934

### LightGBM

In [76]:
for c in X.columns:
    col_type = X[c].dtype
    if col_type == 'str':
        Xtrain[c] = Xtrain[c].astype('category')
        Xtest[c] = Xtest[c].astype('category')

In [108]:
model = LGBMClassifier(random_state=RANDOM_STATE)

model.fit(Xtrain, ytrain)

pred = model.predict_proba(Xtest)[:,1]

roc_auc_score(ytest, pred)

[LightGBM] [Info] Number of positive: 14346, number of negative: 60654
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000601 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 75000, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.191280 -> initscore=-1.441714
[LightGBM] [Info] Start training from score -1.441714

0.7341149074685321

## Выделим дополнительную валидационную выборку

In [78]:
Xtrain_new, Xval, ytrain_new, yval = train_test_split(Xtrain, ytrain, test_size=0.25, random_state=RANDOM_STATE)

Создайте функцию objective_lgbm, в которой среди гиперпараметров

* num_leaves = trial.suggest_int("num_leaves", 10, 100)
* n_estimators = trial.suggest_int("n_estimators", 10, 1000)

подберите оптимальные, обучая **LGBM** на Xtrain_new, ytrain_new и проверяя качество (ROC-AUC) на Xval.

Используйте 30 эпох обучения Optuna.

In [99]:
def objective_LGBM(trial):
    num_leaves = trial.suggest_int("num_leaves", 10, 100)
    max_depth = trial.suggest_int("max_depth", 2, 20)
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1, log = True)
    n_estimators = trial.suggest_int("n_estimators", 10, 1000)
    
    model = LGBMClassifier()
    model.fit(Xtrain_new, ytrain_new)
    pred = model.predict_proba(Xval)[:,1]
    
    score = roc_auc_score(yval, pred)
    
    return score

In [103]:
study = optuna.create_study(direction = 'maximize')
study.optimize(objective_LGBM, n_trials = 100)

[I 2026-03-16 19:16:33,703] A new study created in memory with name: no-name-6ec447ba-916b-4ea0-b887-ee3f90611c14

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000330 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:34,072] Trial 0 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 19, 'max_depth': 6, 'learning_rate': 0.03484893612036243, 'n_estimators': 914}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000341 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:34,426] Trial 1 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 86, 'max_depth': 4, 'learning_rate': 0.3429320583073637, 'n_estimators': 657}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000320 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:34,759] Trial 2 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 30, 'max_depth': 6, 'learning_rate': 0.00011069005359965221, 'n_estimators': 53}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:35,101] Trial 3 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 30, 'max_depth': 20, 'learning_rate': 2.8895193894215974e-05, 'n_estimators': 253}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:35,440] Trial 4 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 84, 'max_depth': 10, 'learning_rate': 0.0099416881613653, 'n_estimators': 32}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000327 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:35,815] Trial 5 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 57, 'max_depth': 9, 'learning_rate': 0.00037609489030506166, 'n_estimators': 314}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000362 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:36,193] Trial 6 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 22, 'max_depth': 12, 'learning_rate': 0.0039238636604623164, 'n_estimators': 294}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:36,582] Trial 7 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 97, 'max_depth': 15, 'learning_rate': 1.0754710506896477e-05, 'n_estimators': 358}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000405 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:36,979] Trial 8 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 55, 'max_depth': 10, 'learning_rate': 5.560936804884186e-05, 'n_estimators': 780}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000370 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:37,322] Trial 9 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 58, 'max_depth': 20, 'learning_rate': 3.073122989979578e-05, 'n_estimators': 554}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000383 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:37,709] Trial 10 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 15, 'max_depth': 2, 'learning_rate': 0.20387745940534074, 'n_estimators': 990}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001329 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:38,086] Trial 11 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 78, 'max_depth': 3, 'learning_rate': 0.5322941817242111, 'n_estimators': 733}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000327 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:38,441] Trial 12 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 39, 'max_depth': 5, 'learning_rate': 0.045829424648712105, 'n_estimators': 988}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:38,826] Trial 13 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 77, 'max_depth': 7, 'learning_rate': 0.04789182798069101, 'n_estimators': 751}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000500 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:39,206] Trial 14 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 99, 'max_depth': 4, 'learning_rate': 0.7826121323367822, 'n_estimators': 648}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000400 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:39,569] Trial 15 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 44, 'max_depth': 7, 'learning_rate': 0.07103552368593807, 'n_estimators': 868}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000324 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:39,943] Trial 16 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 70, 'max_depth': 13, 'learning_rate': 0.015516548246285544, 'n_estimators': 506}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:40,301] Trial 17 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 44, 'max_depth': 2, 'learning_rate': 0.0011518048444978458, 'n_estimators': 865}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000359 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:40,667] Trial 18 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 10, 'max_depth': 8, 'learning_rate': 0.14344788382178905, 'n_estimators': 884}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000404 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:41,077] Trial 19 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 89, 'max_depth': 5, 'learning_rate': 0.3427048898218716, 'n_estimators': 629}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000365 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:41,449] Trial 20 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 67, 'max_depth': 16, 'learning_rate': 0.010644128049012363, 'n_estimators': 443}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000416 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:41,811] Trial 21 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 29, 'max_depth': 6, 'learning_rate': 0.00035788193207410106, 'n_estimators': 36}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000315 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:42,179] Trial 22 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 21, 'max_depth': 4, 'learning_rate': 0.0015347276784257041, 'n_estimators': 218}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:42,548] Trial 23 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 33, 'max_depth': 6, 'learning_rate': 0.00018387446833039472, 'n_estimators': 160}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000988 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:42,924] Trial 24 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 21, 'max_depth': 8, 'learning_rate': 0.019686634676634722, 'n_estimators': 397}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000338 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:43,323] Trial 25 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 47, 'max_depth': 4, 'learning_rate': 0.13024948066397984, 'n_estimators': 603}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000360 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:43,715] Trial 26 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 10, 'max_depth': 6, 'learning_rate': 0.004145657640028473, 'n_estimators': 142}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000328 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:44,077] Trial 27 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 35, 'max_depth': 2, 'learning_rate': 0.9255676193493978, 'n_estimators': 703}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000334 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:44,459] Trial 28 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 24, 'max_depth': 8, 'learning_rate': 0.029113396671641978, 'n_estimators': 812}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:44,849] Trial 29 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 28, 'max_depth': 11, 'learning_rate': 9.954055607525548e-05, 'n_estimators': 453}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:45,357] Trial 30 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 52, 'max_depth': 18, 'learning_rate': 0.0013297188229048182, 'n_estimators': 923}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000322 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:45,758] Trial 31 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 39, 'max_depth': 13, 'learning_rate': 1.05028678158667e-05, 'n_estimators': 12}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:46,159] Trial 32 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 65, 'max_depth': 20, 'learning_rate': 3.0365475703678517e-05, 'n_estimators': 95}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000319 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:46,536] Trial 33 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 16, 'max_depth': 10, 'learning_rate': 0.0004790170930215994, 'n_estimators': 264}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:46,936] Trial 34 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 88, 'max_depth': 15, 'learning_rate': 0.006650424076355072, 'n_estimators': 197}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001007 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:47,298] Trial 35 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 33, 'max_depth': 18, 'learning_rate': 2.270838693412815e-05, 'n_estimators': 329}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000321 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:47,692] Trial 36 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 27, 'max_depth': 9, 'learning_rate': 6.560087190768668e-05, 'n_estimators': 109}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000972 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:48,050] Trial 37 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 61, 'max_depth': 12, 'learning_rate': 0.00015779861504025574, 'n_estimators': 268}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000352 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:48,429] Trial 38 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 16, 'max_depth': 3, 'learning_rate': 1.9051018149488376e-05, 'n_estimators': 575}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000363 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:48,791] Trial 39 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 77, 'max_depth': 5, 'learning_rate': 0.30271503813819234, 'n_estimators': 68}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:49,143] Trial 40 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 51, 'max_depth': 9, 'learning_rate': 0.09217899484454686, 'n_estimators': 515}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000326 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:49,527] Trial 41 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 91, 'max_depth': 7, 'learning_rate': 0.006171772444453512, 'n_estimators': 681}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:49,891] Trial 42 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 83, 'max_depth': 11, 'learning_rate': 0.03275350549352538, 'n_estimators': 56}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000389 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:50,299] Trial 43 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 71, 'max_depth': 14, 'learning_rate': 0.002548405566370988, 'n_estimators': 224}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000316 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:50,696] Trial 44 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 95, 'max_depth': 3, 'learning_rate': 4.7593401264566486e-05, 'n_estimators': 156}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000328 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:51,097] Trial 45 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 38, 'max_depth': 18, 'learning_rate': 0.010223370540586616, 'n_estimators': 372}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000394 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:51,499] Trial 46 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 80, 'max_depth': 9, 'learning_rate': 0.0007182793293562766, 'n_estimators': 774}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000327 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:51,881] Trial 47 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 84, 'max_depth': 5, 'learning_rate': 0.06585171397259076, 'n_estimators': 109}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000401 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:52,241] Trial 48 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 19, 'max_depth': 10, 'learning_rate': 0.39361719063031786, 'n_estimators': 975}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000324 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:52,625] Trial 49 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 74, 'max_depth': 7, 'learning_rate': 0.1876756124165949, 'n_estimators': 804}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:52,979] Trial 50 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 25, 'max_depth': 16, 'learning_rate': 0.0021505822861109577, 'n_estimators': 12}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000391 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:53,338] Trial 51 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 100, 'max_depth': 11, 'learning_rate': 0.00024845537485116223, 'n_estimators': 315}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000363 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:53,682] Trial 52 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 61, 'max_depth': 6, 'learning_rate': 0.00010758556760127499, 'n_estimators': 534}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000340 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:54,032] Trial 53 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 45, 'max_depth': 8, 'learning_rate': 4.2133839268479195e-05, 'n_estimators': 425}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000357 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:54,373] Trial 54 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 95, 'max_depth': 4, 'learning_rate': 0.0006802935069754585, 'n_estimators': 260}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:54,728] Trial 55 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 57, 'max_depth': 7, 'learning_rate': 7.906432651019285e-05, 'n_estimators': 466}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000316 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:55,078] Trial 56 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 31, 'max_depth': 10, 'learning_rate': 0.02050836351433308, 'n_estimators': 184}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000361 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:55,451] Trial 57 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 13, 'max_depth': 12, 'learning_rate': 0.00014964918030883645, 'n_estimators': 350}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000411 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:55,804] Trial 58 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 86, 'max_depth': 4, 'learning_rate': 0.0002620081483956828, 'n_estimators': 139}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000366 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:56,145] Trial 59 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 41, 'max_depth': 5, 'learning_rate': 0.004576857342585095, 'n_estimators': 73}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000301 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:56,483] Trial 60 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 50, 'max_depth': 6, 'learning_rate': 1.4958018118595997e-05, 'n_estimators': 917}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000324 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:56,847] Trial 61 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 23, 'max_depth': 2, 'learning_rate': 0.012200654063277121, 'n_estimators': 278}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001158 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:57,183] Trial 62 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 18, 'max_depth': 3, 'learning_rate': 0.007858134496395141, 'n_estimators': 306}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000335 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:57,528] Trial 63 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 12, 'max_depth': 19, 'learning_rate': 0.001898020267095329, 'n_estimators': 232}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000320 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:57,873] Trial 64 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 36, 'max_depth': 9, 'learning_rate': 0.003787768246411558, 'n_estimators': 661}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:58,240] Trial 65 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 30, 'max_depth': 12, 'learning_rate': 0.5723619496705256, 'n_estimators': 392}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001186 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:58,628] Trial 66 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 21, 'max_depth': 13, 'learning_rate': 0.0008795653543149047, 'n_estimators': 730}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000403 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:59,010] Trial 67 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 42, 'max_depth': 17, 'learning_rate': 0.03299065835111284, 'n_estimators': 582}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001202 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:59,405] Trial 68 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 26, 'max_depth': 14, 'learning_rate': 3.6248794812346116e-05, 'n_estimators': 113}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000406 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:16:59,771] Trial 69 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 67, 'max_depth': 7, 'learning_rate': 0.00045724618445353195, 'n_estimators': 194}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000986 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:00,116] Trial 70 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 90, 'max_depth': 8, 'learning_rate': 0.023162979656005885, 'n_estimators': 485}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000405 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:00,502] Trial 71 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 93, 'max_depth': 16, 'learning_rate': 1.0080267887726975e-05, 'n_estimators': 346}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000373 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:00,875] Trial 72 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 97, 'max_depth': 15, 'learning_rate': 1.8601145674480186e-05, 'n_estimators': 419}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000326 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:01,250] Trial 73 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 81, 'max_depth': 20, 'learning_rate': 0.013177408968026962, 'n_estimators': 295}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000320 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:01,633] Trial 74 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 87, 'max_depth': 10, 'learning_rate': 0.05408947835987188, 'n_estimators': 243}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:01,993] Trial 75 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 33, 'max_depth': 13, 'learning_rate': 2.5398411569637613e-05, 'n_estimators': 36}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000355 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:02,382] Trial 76 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 74, 'max_depth': 19, 'learning_rate': 1.3755924297856968e-05, 'n_estimators': 630}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000360 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:02,798] Trial 77 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 23, 'max_depth': 5, 'learning_rate': 5.394287298857996e-05, 'n_estimators': 831}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000410 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:03,179] Trial 78 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 18, 'max_depth': 11, 'learning_rate': 0.10042188026274555, 'n_estimators': 370}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000640 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:03,591] Trial 79 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 54, 'max_depth': 9, 'learning_rate': 0.00538568237251213, 'n_estimators': 328}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:03,948] Trial 80 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 28, 'max_depth': 12, 'learning_rate': 0.00010068857202649908, 'n_estimators': 170}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000320 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:04,362] Trial 81 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 61, 'max_depth': 10, 'learning_rate': 0.002953223289591656, 'n_estimators': 873}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000326 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:04,721] Trial 82 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 63, 'max_depth': 14, 'learning_rate': 3.1384336462517315e-05, 'n_estimators': 975}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000333 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:05,115] Trial 83 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 47, 'max_depth': 9, 'learning_rate': 7.90358317251714e-05, 'n_estimators': 766}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000328 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:05,509] Trial 84 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 77, 'max_depth': 6, 'learning_rate': 0.008555889072800454, 'n_estimators': 951}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:05,857] Trial 85 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 92, 'max_depth': 11, 'learning_rate': 5.2977068191703e-05, 'n_estimators': 903}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000411 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:06,260] Trial 86 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 57, 'max_depth': 8, 'learning_rate': 2.1484710347473645e-05, 'n_estimators': 708}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:06,645] Trial 87 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 72, 'max_depth': 10, 'learning_rate': 0.2691944773782231, 'n_estimators': 841}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:07,036] Trial 88 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 21, 'max_depth': 15, 'learning_rate': 0.00013849218593986267, 'n_estimators': 129}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:07,398] Trial 89 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 80, 'max_depth': 4, 'learning_rate': 1.4329859832351543e-05, 'n_estimators': 85}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:07,762] Trial 90 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 53, 'max_depth': 11, 'learning_rate': 0.000203222791880992, 'n_estimators': 35}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000365 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:08,112] Trial 91 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 57, 'max_depth': 20, 'learning_rate': 2.721826852152582e-05, 'n_estimators': 540}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:08,479] Trial 92 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 14, 'max_depth': 19, 'learning_rate': 3.632813559540601e-05, 'n_estimators': 586}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001457 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:08,837] Trial 93 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 59, 'max_depth': 18, 'learning_rate': 0.0011413371644062977, 'n_estimators': 212}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000300 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:09,203] Trial 94 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 48, 'max_depth': 20, 'learning_rate': 6.799607650748927e-05, 'n_estimators': 791}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000355 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:09,573] Trial 95 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 66, 'max_depth': 19, 'learning_rate': 0.9961492093870057, 'n_estimators': 673}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000320 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:09,921] Trial 96 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 95, 'max_depth': 17, 'learning_rate': 1.7584130762077107e-05, 'n_estimators': 529}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000349 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:10,266] Trial 97 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 69, 'max_depth': 2, 'learning_rate': 0.00031132734164658214, 'n_estimators': 295}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000326 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:10,626] Trial 98 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 98, 'max_depth': 8, 'learning_rate': 1.1910715529008453e-05, 'n_estimators': 625}. Best is trial 0 with value: 0.7257924524688594.

[LightGBM] [Info] Number of positive: 10730, number of negative: 45520
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001263 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 56250, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.190756 -> initscore=-1.445108
[LightGBM] [Info] Start training from score -1.445108

[I 2026-03-16 19:17:10,980] Trial 99 finished with value: 0.7257924524688594 and parameters: {'num_leaves': 50, 'max_depth': 4, 'learning_rate': 0.0036281505034227233, 'n_estimators': 488}. Best is trial 0 with value: 0.7257924524688594.

In [104]:
study.best_params

{'num_leaves': 19,
 'max_depth': 6,
 'learning_rate': 0.03484893612036243,
 'n_estimators': 914}

In [105]:
model = LGBMClassifier(**study.best_params) 
model.fit(Xtrain, ytrain)

pred_proba = model.predict_proba(Xtest)[:,1]

roc_auc_score(ytest, pred_proba)

[LightGBM] [Info] Number of positive: 14346, number of negative: 60654
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000464 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1095
[LightGBM] [Info] Number of data points in the train set: 75000, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.191280 -> initscore=-1.441714
[LightGBM] [Info] Start training from score -1.441714

0.735463718791334

Создайте функцию objective_Cat, в которой среди гиперпараметров

* num_leaves = trial.suggest_int("num_leaves", 10, 100)
* n_estimators = trial.suggest_int("n_estimators", 10, 1000)

подберите оптимальные, обучая **CatBoost** на Xtrain_new, ytrain_new и проверяя качество (ROC-AUC) на Xval.

Используйте 30 эпох обучения Optuna.

In [111]:
def objective_Cat(trial):
    num_leaves = trial.suggest_int("num_leaves", 10, 100)
    #max_depth = trial.suggest_int("max_depth", 2, 20)
    #learning_rate = trial.suggest_float("learning_rate", 1e-5, 1, log = True)
    n_estimators = trial.suggest_int("n_estimators", 10, 1000)
    
    model = CatBoostClassifier(
        custom_loss=['AUC']
    )

    model.fit(
        Xtrain_new, ytrain_new,
        cat_features=categorical_features_indices,
        logging_level='Silent'
    )
    
    pred = model.predict_proba(Xval)[:,1]
    
    score = roc_auc_score(yval, pred)
    
    return score

In [112]:
study = optuna.create_study(direction = 'maximize')
study.optimize(objective_Cat, n_trials = 10)

[I 2026-03-16 19:25:12,844] A new study created in memory with name: no-name-3457514e-c043-4fb4-a39b-001fb26850de
[W 2026-03-16 19:25:35,353] Trial 0 failed with parameters: {'num_leaves': 88, 'n_estimators': 299} because of the following error: KeyboardInterrupt('').
Traceback (most recent call last):
  File "C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\e.karandashova.INSIDE\AppData\Local\Temp\ipykernel_6756\821332798.py", line 11, in objective_Cat
    model.fit(
  File "C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages\catboost\core.py", line 5547, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages\catboost\core.py", line 2716, in _fit
    self._train(
  File "C:\Users\e.karandashova.INSIDE\AppData\Local\anaconda3\envs\py11\Lib\site-packages\catboost\core.py", line 1824, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5430, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5479, in _catboost._CatBoost._train
KeyboardInterrupt
[W 2026-03-16 19:25:35,354] Trial 0 failed with value None.

KeyboardInterrupt:

In [ ]:
study.best_params

In [ ]:
model = CatBoostClassifier(custom_loss=['AUC'], **study.best_params) 
model.fit(Xtrain, ytrain)

pred_proba = model.predict_proba(Xtest)[:,1]

roc_auc_score(ytest, pred_proba)